# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 09:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile',
                                       to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
