# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_meetingtemplate_bandwidth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='meetingTemplate名称'),
        ),
    ]
