# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20171116_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='meeting name')),
                ('meetcode', models.CharField(max_length=200, unique=True, verbose_name='meeting code')),
                ('remark', models.CharField(blank=True, default='', max_length=400, verbose_name='remark')),
            ],
        ),
    ]
