# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtemplate',
            name='audioProtocol',
            field=models.CharField(default='4M', max_length=200, verbose_name='音频协议*'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='capalityname',
            field=models.CharField(default='1080P', max_length=200, verbose_name='视频分辨率*'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='videoFrameRate',
            field=models.IntegerField(default=60, verbose_name='视频刷新率*'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='videoProtocol',
            field=models.CharField(default='4M', max_length=200, verbose_name='视频协议*'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetcode',
            field=models.CharField(max_length=200, unique=True, verbose_name='会议编号*'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='会议名称*'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='bandwidth',
            field=models.CharField(default='4000', max_length=200, verbose_name='带宽*'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='会议模板名称*'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.IntegerField(verbose_name='E164 Alias*'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminalIP',
            field=models.GenericIPAddressField(error_messages={'unique': '重复IP,请重新输入!'}, unique=True, verbose_name='IP*'),
        ),
    ]
