# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0006_auto_20171120_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtemplate',
            name='audioProtocol',
            field=models.CharField(default='G.711-ulaw', max_length=200, verbose_name='音频协议*'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='videoProtocol',
            field=models.CharField(default='H.264', max_length=200, verbose_name='视频协议*'),
        ),
    ]
