# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20171121_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='activeInMcu',
            field=models.BooleanField(default=True, verbose_name='是否在mcu列表中'),
        ),
    ]
