# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0009_meeting_activeinmcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='dualFormat',
            field=models.CharField(default='XGA', max_length=200, verbose_name='双流视频格式*'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='dualProtocol',
            field=models.CharField(default='H.264', max_length=200, verbose_name='双流视频协议*'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='dualFormat',
            field=models.CharField(default='XGA', max_length=200, verbose_name='双流视频格式*'),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='dualProtocol',
            field=models.CharField(default='H.264', max_length=200, verbose_name='双流视频协议*'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='videoFrameRate',
            field=models.IntegerField(default=1024, verbose_name='双流带宽*'),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='videoFrameRate',
            field=models.IntegerField(default=1024, verbose_name='双流带宽*'),
        ),
    ]
