# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0012_auto_20171123_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='capalityname',
            field=models.CharField(default='1080P', max_length=200, verbose_name='视频分辨率*'),
        ),
    ]
