# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_meeting_operationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mainMeetRoom',
            field=models.CharField(default='主会场', max_length=200, verbose_name='主会场*'),
        ),
    ]
