# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_meeting_mainmeetroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mainMeetRoomName',
            field=models.CharField(default='', max_length=200, verbose_name='主会场名称*'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mainMeetRoom',
            field=models.CharField(default='', max_length=200, verbose_name='主会场*'),
        ),
    ]
