# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0018_auto_20171219_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcuAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True, verbose_name='MCU别名*')),
                ('logLevel', models.IntegerField(default=0, verbose_name='日志级别*')),
            ],
        ),
    ]
