# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_mcuattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='gkAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP*')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
